/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.uva.eii.dis.floristeriaHolanda.Interfaz;

/**
 *
 * @author super
 */
public class VistaModificarLote extends javax.swing.JFrame {
    
    private final CtrlVistaModificarLote controlador;
    /**
     * Creates new form VistaModificarEstadoLote
     */
  public VistaModificarLote() {
        initComponents();
        selectorLotes.hide();
        jLabel2.hide();
        errorPlanta.hide();
        confirmar.hide();
        estimAviso.hide();
        errorLote.hide();
        errorPlanta.hide();
        jLabel3.hide();
        selectorEstado.hide();
        introducir.hide();
        estimar.hide();
        controlador = new CtrlVistaModificarLote(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        planta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        selectorLotes = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        selectorEstado = new javax.swing.JComboBox<>();
        cancelar = new javax.swing.JButton();
        confirmar = new javax.swing.JButton();
        errorPlanta = new javax.swing.JLabel();
        errorLote = new javax.swing.JLabel();
        estimAviso = new javax.swing.JLabel();
        buscar = new javax.swing.JButton();
        introducir = new javax.swing.JButton();
        noConfirmar = new javax.swing.JButton();
        estimar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        planta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plantaActionPerformed(evt);
            }
        });

        jLabel1.setText("Introducir nombre de la planta:");

        selectorLotes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        jLabel2.setText("Seleccionar lote a cambiar:");

        jLabel3.setText("Seleccionar nuevo estado:");

        selectorEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pendienteDePlantar", "plantado", "enProduccion", "finDeVidaUtil", "eliminado" }));

        cancelar.setText("CancelarOperacion");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        confirmar.setText("Confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });

        errorPlanta.setText("* No hay lotes asociados a la planta");

        errorLote.setText("* El estado introducido no es valido");

        estimAviso.setText("Puede estimar las flores");

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        introducir.setText("Introducir");
        introducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introducirActionPerformed(evt);
            }
        });

        noConfirmar.setText("No confirmar");
        noConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noConfirmarActionPerformed(evt);
            }
        });

        estimar.setText("Estimar flores");
        estimar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estimarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(noConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(estimAviso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(estimar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(introducir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectorLotes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(planta)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 314, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(buscar))
                            .addComponent(selectorEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(errorLote))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(errorPlanta)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(errorPlanta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(planta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(errorLote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectorLotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectorEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estimAviso)
                    .addComponent(introducir)
                    .addComponent(estimar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar)
                    .addComponent(confirmar)
                    .addComponent(noConfirmar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plantaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plantaActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        controlador.procesaEventoPlanta();
    }//GEN-LAST:event_buscarActionPerformed

    private void introducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introducirActionPerformed
        controlador.procesaEventoEstado();
    }//GEN-LAST:event_introducirActionPerformed

    private void noConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noConfirmarActionPerformed
        controlador.noConfirma();
    }//GEN-LAST:event_noConfirmarActionPerformed

    private void estimarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estimarActionPerformed
        controlador.procesaEventoEstim();
    }//GEN-LAST:event_estimarActionPerformed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        controlador.confirmar();
    }//GEN-LAST:event_confirmarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        controlador.cancela();
    }//GEN-LAST:event_cancelarActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton confirmar;
    private javax.swing.JLabel errorLote;
    private javax.swing.JLabel errorPlanta;
    private javax.swing.JLabel estimAviso;
    private javax.swing.JButton estimar;
    private javax.swing.JButton introducir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton noConfirmar;
    private javax.swing.JTextField planta;
    private javax.swing.JComboBox<String> selectorEstado;
    private javax.swing.JComboBox<String> selectorLotes;
    // End of variables declaration//GEN-END:variables

    public String getPlanta() {
        return planta.getText();
    }

    public void mostrarErrorPlanta() {
        errorPlanta.setVisible(true);
    }

    public void addLote(String[] lote) {
        selectorLotes.addItem("ID:" + lote[0]+ " Fecha:" + lote[1] + " Estado:" + lote[2]);
    }

    public void muestraLotes() {
        buscar.hide();
        selectorLotes.setVisible(true);
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        selectorEstado.setVisible(true);
        introducir.setVisible(true);
    }

    public int getLote() {
        String lote = (String) selectorLotes.getSelectedItem();
        String[] parte = lote.split(" ");
        lote = parte[0];
        parte = lote.split(":");
        lote = parte [1];
        int id = Integer.parseInt(lote);
        System.out.println("id seleccionado = "+id);
        return id;
        
    }

    public String getEstado() {
        return (String) selectorEstado.getSelectedItem();
    }

    public void errorEstado() {
        errorLote.setVisible(true);
    }

    public void pedirConfirmacion() {
        introducir.hide();
        errorLote.hide();
        confirmar.setVisible(true);
        noConfirmar.setVisible(true);
    }

    public void muestraIntroducir() {
        estimAviso.hide();
        estimar.hide();
        confirmar.hide();
        noConfirmar.hide();
        introducir.setVisible(true);
    }

    public void muestraEstimar() {
        estimAviso.setVisible(true);
        estimar.setVisible(true);
    }
}
