/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.uva.eii.dis.floristeriaHolanda.Interfaz;

/**
 *
 * @author victo
 */
public class VistaEstimarFlores extends javax.swing.JFrame {
    
    private final CtrlVistaEstimarFlores controlador;

    /**
     * Creates new form VistaAcualizarEstim
     */
    public VistaEstimarFlores(int lote, String planta) {
        initComponents();
        errorNumero.hide();
        errorFlores.hide();
        controlador = new CtrlVistaEstimarFlores(this);
        controlador.procesaEventoInicio(lote, planta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        estimacionText = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        estimacion = new javax.swing.JTextField();
        confirmar = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        errorNumero = new javax.swing.JLabel();
        errorFlores = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Actualización de la estimación de flores");

        estimacionText.setText("Estimación actual:");

        jLabel4.setText("Introducir nueva estimación:");

        estimacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estimacionActionPerformed(evt);
            }
        });

        confirmar.setText("Confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        errorNumero.setText("*Introduzca un numero entero positivo");

        errorFlores.setText("-La planta Introducida no produce flores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estimacion)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(volver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(errorNumero))
                            .addComponent(errorFlores)
                            .addComponent(estimacionText))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(estimacionText)
                .addGap(7, 7, 7)
                .addComponent(errorFlores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(errorNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(estimacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmar)
                    .addComponent(volver))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void estimacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estimacionActionPerformed
       
    }//GEN-LAST:event_estimacionActionPerformed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        controlador.procesaEventoCantidad();
    }//GEN-LAST:event_confirmarActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
       controlador.volver();
    }//GEN-LAST:event_volverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmar;
    private javax.swing.JLabel errorFlores;
    private javax.swing.JLabel errorNumero;
    private javax.swing.JTextField estimacion;
    private javax.swing.JLabel estimacionText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

    public void muestraEstim(int estim) {
        estimacionText.setText(estimacionText.getText()+" " +estim);
    }

    public void errorNoHayFlor() {
        errorFlores.setVisible(true);
        confirmar.hide();
        estimacion.hide();
        estimacionText.hide();
        jLabel4.hide();
    }

    public int getCantidad() {
        try{
            return Integer.parseInt(estimacion.getText());
        }catch(NumberFormatException e){
            return -1;
        }
    }

    public void errorCantidad() {
        errorNumero.show();
    }
}
