/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resultadosBusqueda;

import imagenes.*;
import javax.swing.JPanel;

/**
 *
 * @author rojo
 */
public class VistaBusqueda extends javax.swing.JFrame {
    
    private ControladorVistaBusqueda controlador;
    /**
     * Creates new form BusquedaVista
     */
    public VistaBusqueda() {
        initComponents();
        controlador = new ControladorVistaBusqueda(this);
        imagen(foto1,"casa1.jpg");
        imagen(foto2,"casa2.jpg");
        imagen(foto3,"casa3.jpg");
        cambiaCiudad();
        cambiaUsuario();
        esRegistrado();
    }
    
    public void cambiaUsuario(){
        if(controlador.getModelo().getUsuario() != null){
            usuario.setText(controlador.getModelo().getUsuario());
        }
        
    }
    
    public void esRegistrado(){
        if(controlador.getModelo().esRegistrado()){
            botonIniciaSesion.setVisible(false);
            botonCerrarSesion.setVisible(true);
        }else{
            botonCerrarSesion.setVisible(false);
        }
    }
    
    public void imagen(JPanel panel, String direccion){
        Imagen Imagen = new Imagen(direccion, panel.getSize());
        panel.add(Imagen);
        panel.repaint();
    }
    
    public void cambiaCiudad(){
        ciudad1.setText(controlador.getModelo().getCiudad());
        ciudad2.setText(controlador.getModelo().getCiudad());
        ciudad3.setText(controlador.getModelo().getCiudad());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultados = new javax.swing.JPanel();
        piso1 = new javax.swing.JPanel();
        foto1 = new javax.swing.JPanel();
        nombreetiqueta1 = new javax.swing.JLabel();
        ciudadetiqueta1 = new javax.swing.JLabel();
        habitacionesetiqueta1 = new javax.swing.JLabel();
        precioetiqueta1 = new javax.swing.JLabel();
        metrosetiqueta1 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JLabel();
        ciudad1 = new javax.swing.JLabel();
        habitaciones1 = new javax.swing.JLabel();
        metros1 = new javax.swing.JLabel();
        precio1 = new javax.swing.JLabel();
        reservar1 = new javax.swing.JButton();
        lista1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        piso2 = new javax.swing.JPanel();
        foto2 = new javax.swing.JPanel();
        nombreetiqueta2 = new javax.swing.JLabel();
        ciudadetiqueta2 = new javax.swing.JLabel();
        habitacionesetiqueta2 = new javax.swing.JLabel();
        precioetiqueta2 = new javax.swing.JLabel();
        metrosetiqueta2 = new javax.swing.JLabel();
        nombre2 = new javax.swing.JLabel();
        ciudad2 = new javax.swing.JLabel();
        habitaciones2 = new javax.swing.JLabel();
        metros2 = new javax.swing.JLabel();
        precio2 = new javax.swing.JLabel();
        reservar2 = new javax.swing.JButton();
        lista2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        piso3 = new javax.swing.JPanel();
        foto3 = new javax.swing.JPanel();
        nombreetiqueta3 = new javax.swing.JLabel();
        ciudadetiqueta3 = new javax.swing.JLabel();
        habitacionesetiqueta3 = new javax.swing.JLabel();
        precioetiqueta3 = new javax.swing.JLabel();
        metrosetiqueta3 = new javax.swing.JLabel();
        nombre3 = new javax.swing.JLabel();
        ciudad3 = new javax.swing.JLabel();
        habitaciones3 = new javax.swing.JLabel();
        metros3 = new javax.swing.JLabel();
        precio3 = new javax.swing.JLabel();
        reservar3 = new javax.swing.JButton();
        lista3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        botonIniciaSesion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botonCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        piso1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout foto1Layout = new javax.swing.GroupLayout(foto1);
        foto1.setLayout(foto1Layout);
        foto1Layout.setHorizontalGroup(
            foto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );
        foto1Layout.setVerticalGroup(
            foto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        nombreetiqueta1.setText("Nombre del piso:");

        ciudadetiqueta1.setText("Ciudad:");

        habitacionesetiqueta1.setText("Habitaciones:");

        precioetiqueta1.setText("Precio:");

        metrosetiqueta1.setText("Metros cuadrados:");

        nombre1.setText("Casa Isma");

        habitaciones1.setText("4");

        metros1.setText("120 m2");

        precio1.setText("220");

        reservar1.setText("Reservar");
        reservar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservar1ActionPerformed(evt);
            }
        });

        lista1.setText("Añadir a mi lista");
        lista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lista1ActionPerformed(evt);
            }
        });

        jLabel2.setText("€");

        javax.swing.GroupLayout piso1Layout = new javax.swing.GroupLayout(piso1);
        piso1.setLayout(piso1Layout);
        piso1Layout.setHorizontalGroup(
            piso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piso1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(foto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(piso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(piso1Layout.createSequentialGroup()
                        .addGroup(piso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreetiqueta1)
                            .addComponent(ciudadetiqueta1)
                            .addComponent(habitacionesetiqueta1))
                        .addGap(32, 32, 32)
                        .addGroup(piso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(piso1Layout.createSequentialGroup()
                                .addComponent(nombre1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addGap(259, 259, 259))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, piso1Layout.createSequentialGroup()
                                .addComponent(ciudad1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(piso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lista1)
                                    .addComponent(reservar1)))
                            .addGroup(piso1Layout.createSequentialGroup()
                                .addComponent(habitaciones1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(piso1Layout.createSequentialGroup()
                        .addGroup(piso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(metrosetiqueta1)
                            .addComponent(precioetiqueta1))
                        .addGap(18, 18, 18)
                        .addGroup(piso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(metros1)
                            .addGroup(piso1Layout.createSequentialGroup()
                                .addComponent(precio1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))))
                .addGap(46, 46, 46))
        );
        piso1Layout.setVerticalGroup(
            piso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piso1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(piso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(piso1Layout.createSequentialGroup()
                        .addGroup(piso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreetiqueta1)
                            .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(piso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ciudad1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(piso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ciudadetiqueta1)
                                .addComponent(reservar1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(piso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(habitacionesetiqueta1)
                            .addComponent(habitaciones1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(piso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(metrosetiqueta1)
                            .addComponent(metros1)
                            .addComponent(lista1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(piso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(precioetiqueta1)
                            .addComponent(precio1)
                            .addComponent(jLabel2)))
                    .addComponent(foto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        piso2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        piso2.setPreferredSize(new java.awt.Dimension(678, 155));

        javax.swing.GroupLayout foto2Layout = new javax.swing.GroupLayout(foto2);
        foto2.setLayout(foto2Layout);
        foto2Layout.setHorizontalGroup(
            foto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );
        foto2Layout.setVerticalGroup(
            foto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        nombreetiqueta2.setText("Nombre del piso:");

        ciudadetiqueta2.setText("Ciudad:");

        habitacionesetiqueta2.setText("Habitaciones:");

        precioetiqueta2.setText("Precio:");

        metrosetiqueta2.setText("Metros cuadrados:");

        nombre2.setText("Casa Victor");

        habitaciones2.setText("3");

        metros2.setText("95 m2");

        precio2.setText("195");

        reservar2.setText("Reservar");
        reservar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservar2ActionPerformed(evt);
            }
        });

        lista2.setText("Añadir a mi lista");
        lista2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lista2ActionPerformed(evt);
            }
        });

        jLabel3.setText("€");

        javax.swing.GroupLayout piso2Layout = new javax.swing.GroupLayout(piso2);
        piso2.setLayout(piso2Layout);
        piso2Layout.setHorizontalGroup(
            piso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piso2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(foto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(piso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(piso2Layout.createSequentialGroup()
                        .addGroup(piso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreetiqueta2)
                            .addComponent(ciudadetiqueta2)
                            .addComponent(habitacionesetiqueta2))
                        .addGroup(piso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(piso2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(habitaciones2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, piso2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(piso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombre2, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                    .addComponent(ciudad2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(piso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lista2)
                                    .addComponent(reservar2)))))
                    .addGroup(piso2Layout.createSequentialGroup()
                        .addGroup(piso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(metrosetiqueta2)
                            .addComponent(precioetiqueta2))
                        .addGap(18, 18, 18)
                        .addGroup(piso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(metros2)
                            .addGroup(piso2Layout.createSequentialGroup()
                                .addComponent(precio2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))))
                .addGap(46, 46, 46))
        );
        piso2Layout.setVerticalGroup(
            piso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piso2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(piso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(piso2Layout.createSequentialGroup()
                        .addGroup(piso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreetiqueta2)
                            .addComponent(nombre2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(piso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ciudadetiqueta2)
                            .addComponent(ciudad2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reservar2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(piso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(habitacionesetiqueta2)
                            .addComponent(habitaciones2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(piso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(metrosetiqueta2)
                            .addComponent(metros2)
                            .addComponent(lista2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(piso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(precioetiqueta2)
                            .addComponent(precio2)
                            .addComponent(jLabel3))
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(piso2Layout.createSequentialGroup()
                        .addComponent(foto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        piso3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout foto3Layout = new javax.swing.GroupLayout(foto3);
        foto3.setLayout(foto3Layout);
        foto3Layout.setHorizontalGroup(
            foto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );
        foto3Layout.setVerticalGroup(
            foto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        nombreetiqueta3.setText("Nombre del piso:");

        ciudadetiqueta3.setText("Ciudad:");

        habitacionesetiqueta3.setText("Habitaciones:");

        precioetiqueta3.setText("Precio:");

        metrosetiqueta3.setText("Metros cuadrados:");

        nombre3.setText("Casa Felix");

        habitaciones3.setText("2");

        metros3.setText("80 m2");

        precio3.setText("150");

        reservar3.setText("Reservar");
        reservar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservar3ActionPerformed(evt);
            }
        });

        lista3.setText("Añadir a mi lista");
        lista3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lista3ActionPerformed(evt);
            }
        });

        jLabel4.setText("€");

        javax.swing.GroupLayout piso3Layout = new javax.swing.GroupLayout(piso3);
        piso3.setLayout(piso3Layout);
        piso3Layout.setHorizontalGroup(
            piso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piso3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(foto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(piso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(piso3Layout.createSequentialGroup()
                        .addGroup(piso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreetiqueta3)
                            .addComponent(ciudadetiqueta3)
                            .addComponent(habitacionesetiqueta3))
                        .addGap(32, 32, 32)
                        .addGroup(piso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, piso3Layout.createSequentialGroup()
                                .addGroup(piso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombre3, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                    .addComponent(ciudad3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(piso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lista3)
                                    .addComponent(reservar3)))
                            .addComponent(habitaciones3)))
                    .addGroup(piso3Layout.createSequentialGroup()
                        .addGroup(piso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(metrosetiqueta3)
                            .addComponent(precioetiqueta3))
                        .addGap(18, 18, 18)
                        .addGroup(piso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(metros3)
                            .addGroup(piso3Layout.createSequentialGroup()
                                .addComponent(precio3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))))
                .addGap(46, 46, 46))
        );
        piso3Layout.setVerticalGroup(
            piso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piso3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(piso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(piso3Layout.createSequentialGroup()
                        .addGroup(piso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreetiqueta3)
                            .addComponent(nombre3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(piso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ciudadetiqueta3)
                            .addComponent(ciudad3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reservar3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(piso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(habitacionesetiqueta3)
                            .addComponent(habitaciones3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(piso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(metrosetiqueta3)
                            .addComponent(metros3)
                            .addComponent(lista3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(piso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(precioetiqueta3)
                            .addComponent(precio3)
                            .addComponent(jLabel4))
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(piso3Layout.createSequentialGroup()
                        .addComponent(foto3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        botonIniciaSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iniciosesion.png"))); // NOI18N
        botonIniciaSesion.setText("Iniciar Sesion");
        botonIniciaSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciaSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonIniciaSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonIniciaSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout resultadosLayout = new javax.swing.GroupLayout(resultados);
        resultados.setLayout(resultadosLayout);
        resultadosLayout.setHorizontalGroup(
            resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(piso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(piso3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(piso2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultadosLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(415, 415, 415)
                        .addComponent(botonVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        resultadosLayout.setVerticalGroup(
            resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(piso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(piso2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(piso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Resultados de la busqueda");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        usuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        botonCerrarSesion.setText("Cerrar sesion");
        botonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonCerrarSesion)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonCerrarSesion)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        controlador.backVentana();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonIniciaSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciaSesionActionPerformed
        controlador.loguin();
    }//GEN-LAST:event_botonIniciaSesionActionPerformed

    private void botonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesionActionPerformed
        botonIniciaSesion.setVisible(true);
        botonCerrarSesion.setVisible(false);
        usuario.setText(null);
        controlador.resetUsuario();
    }//GEN-LAST:event_botonCerrarSesionActionPerformed

    private void reservar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservar1ActionPerformed
        controlador.reservar(nombre1.getText(), precio1.getText(), habitaciones1.getText());
    }//GEN-LAST:event_reservar1ActionPerformed

    private void reservar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservar2ActionPerformed
        controlador.reservar(nombre2.getText(), precio2.getText(), habitaciones2.getText());
    }//GEN-LAST:event_reservar2ActionPerformed

    private void reservar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservar3ActionPerformed
        controlador.reservar(nombre1.getText(), precio3.getText(), habitaciones3.getText());
    }//GEN-LAST:event_reservar3ActionPerformed

    private void lista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista1ActionPerformed
        controlador.añadirListaDeseos(nombre1.getText(), precio1.getText(), habitaciones1.getText());
    }//GEN-LAST:event_lista1ActionPerformed

    private void lista2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista2ActionPerformed
        controlador.añadirListaDeseos(nombre2.getText(), precio2.getText(), habitaciones2.getText());
    }//GEN-LAST:event_lista2ActionPerformed

    private void lista3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista3ActionPerformed
        controlador.añadirListaDeseos(nombre1.getText(), precio3.getText(), habitaciones3.getText());
    }//GEN-LAST:event_lista3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaBusqueda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrarSesion;
    private javax.swing.JButton botonIniciaSesion;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel ciudad1;
    private javax.swing.JLabel ciudad2;
    private javax.swing.JLabel ciudad3;
    private javax.swing.JLabel ciudadetiqueta1;
    private javax.swing.JLabel ciudadetiqueta2;
    private javax.swing.JLabel ciudadetiqueta3;
    private javax.swing.JPanel foto1;
    private javax.swing.JPanel foto2;
    private javax.swing.JPanel foto3;
    private javax.swing.JLabel habitaciones1;
    private javax.swing.JLabel habitaciones2;
    private javax.swing.JLabel habitaciones3;
    private javax.swing.JLabel habitacionesetiqueta1;
    private javax.swing.JLabel habitacionesetiqueta2;
    private javax.swing.JLabel habitacionesetiqueta3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton lista1;
    private javax.swing.JButton lista2;
    private javax.swing.JButton lista3;
    private javax.swing.JLabel metros1;
    private javax.swing.JLabel metros2;
    private javax.swing.JLabel metros3;
    private javax.swing.JLabel metrosetiqueta1;
    private javax.swing.JLabel metrosetiqueta2;
    private javax.swing.JLabel metrosetiqueta3;
    private javax.swing.JLabel nombre1;
    private javax.swing.JLabel nombre2;
    private javax.swing.JLabel nombre3;
    private javax.swing.JLabel nombreetiqueta1;
    private javax.swing.JLabel nombreetiqueta2;
    private javax.swing.JLabel nombreetiqueta3;
    private javax.swing.JPanel piso1;
    private javax.swing.JPanel piso2;
    private javax.swing.JPanel piso3;
    private javax.swing.JLabel precio1;
    private javax.swing.JLabel precio2;
    private javax.swing.JLabel precio3;
    private javax.swing.JLabel precioetiqueta1;
    private javax.swing.JLabel precioetiqueta2;
    private javax.swing.JLabel precioetiqueta3;
    private javax.swing.JButton reservar1;
    private javax.swing.JButton reservar2;
    private javax.swing.JButton reservar3;
    private javax.swing.JPanel resultados;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
