/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.uva.eii.dis.floristeriaHolanda.Interfaz.paresVistaControl.login;

/**
 *
 * @author super
 */
public class VistaIdentificarse extends javax.swing.JFrame {

    private final ControladorVistaIdentificarse controlador;
    
    /**
     * Creates new form VistaLogin
     */
    public VistaIdentificarse() {
        initComponents();
        labelLoginIncorrecto.setVisible(false);
        jTextArea2.setVisible(false);
        controlador = new ControladorVistaIdentificarse(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textDNI = new javax.swing.JTextField();
        botonIdentificarse = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        botonAyuda = new javax.swing.JButton();
        labelLoginIncorrecto = new javax.swing.JLabel();
        panelInformacion = new javax.swing.JPanel();
        jTextArea2 = new javax.swing.JTextArea();
        labelDNI = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        textPassword = new javax.swing.JPasswordField();
        verContraseña = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Identificación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));

        textDNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textDNIFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textDNIFocusLost(evt);
            }
        });
        textDNI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textDNIMouseClicked(evt);
            }
        });
        textDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDNIActionPerformed(evt);
            }
        });

        botonIdentificarse.setText("Identificarse");
        botonIdentificarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonIdentificarseMouseClicked(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.setPreferredSize(new java.awt.Dimension(101, 32));
        botonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSalirMouseClicked(evt);
            }
        });

        botonAyuda.setText("Ayuda");
        botonAyuda.setPreferredSize(new java.awt.Dimension(101, 32));
        botonAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAyudaMouseClicked(evt);
            }
        });

        labelLoginIncorrecto.setFocusable(false);

        panelInformacion.setPreferredSize(new java.awt.Dimension(264, 48));

        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(3);
        jTextArea2.setText("Debe introducir sus credenciales de empleado, DNI y contraseña, y será redirigido a las funciones del sistema que le correspondan.");
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setAutoscrolls(false);
        jTextArea2.setFocusable(false);
        jTextArea2.setOpaque(false);

        javax.swing.GroupLayout panelInformacionLayout = new javax.swing.GroupLayout(panelInformacion);
        panelInformacion.setLayout(panelInformacionLayout);
        panelInformacionLayout.setHorizontalGroup(
            panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, Short.MAX_VALUE))
        );
        panelInformacionLayout.setVerticalGroup(
            panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
            .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTextArea2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
        );

        labelDNI.setText("DNI");

        labelPassword.setText("Contraseña");

        verContraseña.setText("Ver Password");
        verContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verContraseñaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonIdentificarse))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPassword)
                            .addComponent(labelDNI))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textDNI)
                            .addComponent(textPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(verContraseña))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelLoginIncorrecto, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(botonAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 128, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDNI))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPassword)
                    .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verContraseña))
                .addGap(15, 15, 15)
                .addComponent(labelLoginIncorrecto, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonIdentificarse)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textDNIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textDNIMouseClicked
        setDNI("");
    }//GEN-LAST:event_textDNIMouseClicked

    private void textDNIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textDNIFocusLost
        
    }//GEN-LAST:event_textDNIFocusLost

    private void textDNIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textDNIFocusGained
        
    }//GEN-LAST:event_textDNIFocusGained

    private void botonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseClicked
        controlador.salir();
    }//GEN-LAST:event_botonSalirMouseClicked

    private void botonAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAyudaMouseClicked
        mostrarAyuda();
    }//GEN-LAST:event_botonAyudaMouseClicked

    private void botonIdentificarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIdentificarseMouseClicked
        controlador.procesaEventoIdentificarse();
    }//GEN-LAST:event_botonIdentificarseMouseClicked

    private void textDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDNIActionPerformed

    private void verContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verContraseñaActionPerformed
        controlador.setPasswordVisible();
    }//GEN-LAST:event_verContraseñaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAyuda;
    private javax.swing.JButton botonIdentificarse;
    private javax.swing.JButton botonSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel labelDNI;
    private javax.swing.JLabel labelLoginIncorrecto;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JPanel panelInformacion;
    private javax.swing.JTextField textDNI;
    private javax.swing.JPasswordField textPassword;
    private javax.swing.JCheckBox verContraseña;
    // End of variables declaration//GEN-END:variables
 
    
    public String getDNI() {
        return textDNI.getText();
    }
    private void setDNI(String dni) {
        textDNI.setText(dni);
    }
    
    public String getPassword() {
        return textPassword.getText();
    }
    
    private void setContraseña(String pass) {
        textPassword.setText(pass);
    }

    private void mostrarAyuda() {
        if(!jTextArea2.isVisible()){
            jTextArea2.setVisible(true);
        }else{
            jTextArea2.setVisible(false);
        }
    }
    
    protected void mostrarErrorLogin() {
        labelLoginIncorrecto.setText("El usuario y la contraseña no coinciden");
        labelLoginIncorrecto.setVisible(true);
    }
    
    protected void mostrarErrorActivo() {
        labelLoginIncorrecto.setText("El usuario introducido no está activo");
        labelLoginIncorrecto.setVisible(true);
    }
    
    
    public boolean verPasswordSelected(){
        return verContraseña.isSelected();
    }
    
    public void setPasswordVisible(char c){
        textPassword.setEchoChar(c);
    }
}





